### ISSUE TITLE
Missing prereq specifications

### ISSUE THREAD

**Issue by eserte** [kablamo/Net-Amazon-DynamoDB-Table#1]
It seems that at least two modules are not specified as a prerequisite, so tests may fail:
- JSON::XS (see http://www.cpantesters.org/cpan/report/de1681c8-e2a6-11e5-8efc-839bfcd2507e )
- DDP (CPAN Testers fail report will appear in a few hours)

**Comment by kablamo** [comment]
Thanks!  Fixed.  Just did a release.
